### ISSUE TITLE
Django 1.7 problem?

### ISSUE THREAD

**Issue by petkostas** [jazzband/sorl-thumbnail#266]
Hello I am experiencing problems with sorl and django 1.7 (testing environment):

```
(zenbframework)vagrant@precise64:/python-projects/zenbframework/zenframework$ pip freeze
Django==1.7b1
Pillow==2.4.0
argparse==1.2.1
django-braces==1.4.0
django-crispy-forms==1.4.0
django-mptt==0.6.0
redis==2.9.1
six==1.6.1
sorl-thumbnail==11.12
unicode-slugify==0.1.1
wsgiref==0.1.2
```

My settings:

```
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'sorl.thumbnail',
    'posts',
    'news',
)
```

Trying to run migrate (replaces syncdb):

```
(zenbframework)vagrant@precise64:/python-projects/zenbframework/zenframework$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/zenbframework/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 427, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/zenbframework/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 391, in execute
    django.setup()
  File "/home/vagrant/.virtualenvs/zenbframework/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/.virtualenvs/zenbframework/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/vagrant/.virtualenvs/zenbframework/local/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
    "cannot import name '%s' from '%s'" % (cls_name, mod_path))
ImportError: cannot import name 'thumbnail' from 'sorl'
```

**Comment by jonthdiaz** [comment]
Thanks you!

**Comment by SalahAdDin** [comment]
Hey, now you can use pip install, the last version is 12.2

**Comment by r05** [comment]
nice! thanks a lot

**Comment by ricardokamada** [comment]
Thanks
Em 15/01/2015 04:25, "Ros" <notifications@github.com> escreveu:
