### ISSUE TITLE
AdminImageMixin doesn't works in Django 1.9.3

### ISSUE THREAD

**Issue by SalahAdDin** [jazzband/sorl-thumbnail#448]
Hi, how are you?

Never before i had have problems with  Sorl Thumbnail, but now i have it:
![modificar professional sitio de administracion de django - opera_030](https://cloud.githubusercontent.com/assets/5034215/13656275/7b018340-e633-11e5-9bb8-b8f496c78d41.png)
As you can see, `AdminImageMixin` doesn't show me anyt thumbnail from photo profile.
![seleccion_031](https://cloud.githubusercontent.com/assets/5034215/13656277/7beb782e-e633-11e5-8e0c-4d6956f35ba0.png)
But you can see here that this image exist, and was saved.
![seleccion_034](https://cloud.githubusercontent.com/assets/5034215/13656316/cda54b18-e633-11e5-91f9-4e341ade5f07.png)
Here i try to see in REST Api and i can see it:
![seleccion_032](https://cloud.githubusercontent.com/assets/5034215/13656278/7bf1bdec-e633-11e5-9ccf-6739e9ad27c1.png)
And here i can't see the image, so, the url it's correct, but `AdminImageMixin` can't show me anything.

So, i try test the thumbnail using the `get_thumbnail` function and i have this problem:

``` bash
(quotation) [salahaddin@TulipanROG quotation]$ ./manage.py shell_plus
# Shell Plus Model Imports
from django.contrib.admin.models import LogEntry
from django.contrib.auth.models import Group, Permission, User
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions.models import Session
from django.contrib.sites.models import Site
from jet.dashboard.models import UserDashboardModule
from jet.models import Bookmark, PinnedApplication
from professional.models import Area, Department, Profession, Professional
from robots.models import Rule, Url
from sorl.thumbnail.models import KVStore
# Shell Plus Django Imports
from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils import timezone
from django.db.models import Avg, Count, F, Max, Min, Sum, Q, Prefetch, Case, When
from django.db import transaction
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> User
<class 'django.contrib.auth.models.User'>
>>> Professional
<class 'professional.models.Professional'>
>>> Professional.objects.all()
[<Professional:  >]
>>> Professional.objects.get(id=1)
<Professional:  >
>>> print (Professional.objects.get(id=1).photo)
images/professional_profile_photo/2016-03-02-123508.jpg
>>> get_thumbnail(Professional.objects.get(id=1).photo, '100x100')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'get_thumbnail' is not defined
>>> from sorl.thumbnail import get_thumbnail
>>> get_thumbnail(Professional.objects.get(id=1).photo, '100x100')
Traceback (most recent call last):
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: no existe la relación «thumbnail_kvstore»
LINE 1: ..._kvstore"."key", "thumbnail_kvstore"."value" FROM "thumbnail...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/sorl/thumbnail/shortcuts.py", line 8, in get_thumbnail
    return default.backend.get_thumbnail(file_, geometry_string, **options)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/sorl/thumbnail/base.py", line 94, in get_thumbnail
    cached = default.kvstore.get(thumbnail)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/sorl/thumbnail/kvstores/base.py", line 26, in get
    return self._get(image_file.key)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/sorl/thumbnail/kvstores/base.py", line 145, in _get
    value = self._get_raw(add_prefix(key, identity))
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/sorl/thumbnail/kvstores/cached_db_kvstore.py", line 36, in _get_raw
    value = KVStoreModel.objects.get(key=key).value
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/quotation/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: no existe la relación «thumbnail_kvstore»
LINE 1: ..._kvstore"."key", "thumbnail_kvstore"."value" FROM "thumbnail...
                                                             ^
```

Can't you help me?

**Comment by mariocesar** [comment]
Are you using the latest dev version? 

```pip install --pre sorl-thumbnail```

**Comment by SalahAdDin** [comment]
No, i'm using the current version.

**Comment by wernight** [comment]
Related to this issue, I'd document on https://sorl-thumbnail.readthedocs.org/en/latest/examples.html#admin-examples about the expected features/benefit of using that admin interface.

**Comment by SalahAdDin** [comment]
@mariocesar I found the solution [here](http://stackoverflow.com/a/35883910/3826549).

I think so that, at least in pypi package, some migrations are missing.

**Comment by fabiocaccamo** [comment]
Thanks @SalahAdDin for the solution.
@mariocesar could you fix it?

**Comment by SalahAdDin** [comment]
@mariocesar Please.

**Comment by claudep** [comment]
I guess this issue is obsolete, reopen if that can be reproduced on modern Django.
