### ISSUE TITLE
Error with django 1.11 Memcached options.

### ISSUE THREAD

**Issue by jpmcaqp** [jazzband/sorl-thumbnail#499]
In django 1.11 Cache
Memcached backends now pass the contents of OPTIONS as keyword arguments to the client constructors, allowing for more advanced control of client behavior. See the cache arguments documentation for examples.

```[ERROR] [30/May/2017 17:20:39] Thumbnail tag failed
Traceback (most recent call last):
  File "/home/jpmcproject/src/sorl-thumbnail/sorl/thumbnail/templatetags/thumbnail.py", line 60, in render
    return self._render(context)
  File "/home/jpmcproject/src/sorl-thumbnail/sorl/thumbnail/templatetags/thumbnail.py", line 138, in _render
    thumbnail = get_thumbnail(file_, geometry, **options)
  File "/home/jpmcproject/src/sorl-thumbnail/sorl/thumbnail/shortcuts.py", line 8, in get_thumbnail
    return default.backend.get_thumbnail(file_, geometry_string, **options)
  File "/home/jpmcproject/src/sorl-thumbnail/sorl/thumbnail/base.py", line 102, in get_thumbnail
    cached = default.kvstore.get(thumbnail)
  File "/home/jpmcproject/src/sorl-thumbnail/sorl/thumbnail/kvstores/base.py", line 26, in get
    return self._get(image_file.key)
  File "/home/jpmcproject/src/sorl-thumbnail/sorl/thumbnail/kvstores/base.py", line 145, in _get
    value = self._get_raw(add_prefix(key, identity))
  File "/home/jpmcproject/src/sorl-thumbnail/sorl/thumbnail/kvstores/cached_db_kvstore.py", line 36, in _get_raw
    value = self.cache.get(key)
  File "/home/jpmcproject/lib/python3.4/site-packages/django/core/cache/backends/memcached.py", line 79, in get
    val = self._cache.get(key)
  File "/home/jpmcproject/lib/python3.4/site-packages/django/core/cache/backends/memcached.py", line 172, in _cache
    self._client = self._lib.Client(self._servers, **client_kwargs)
TypeError: __init__() got an unexpected keyword argument 'MAX_ENTRIES'

**Comment by jpmcpe** [comment]
Resolve, the error MAX_ENTRIES is for incompatibility of python3-memcached and django 1.11
here the incompatibility solution  
replace python-memcached for ->  https://github.com/jpmcpe/python3-memcached#egg=python3_memcached

**Comment by timgraham** [comment]
As far as I can tell, this has nothing to do with sorl-thumbnail. From the Django documentation:
>  Cache backends that implement their own culling strategy (i.e., the locmem, filesystem and database backends) will honor the following options: ... MAX_ENTRIES.

memcached doesn't support MAX_ENTRIES so you need to remove that from your cache configuration.
