### ISSUE TITLE
Applying thumbnail.0001_initial...Traceback (most recent call last)

### ISSUE THREAD

**Issue by jpuaux** [jazzband/sorl-thumbnail#587]
Hi,

I have recently upgraded from Django 1.9.2 to Django 1.11.20. I am using sorl-thumbnail 12.5.

I made a few update, then ran makemigrations and got the following error:

```
Operations to perform:
  Apply all migrations: account, activatepictures, admin, auth, authtoken, autotweet, contenttypes, fileupload, googleautocomplete, locationreview, naturalearth, searchmydestiny, sessions, sites, socialaccount, thumbnail, trip, usermanagement, welcomepage, world
Running migrations:
  Applying auth.0008_alter_user_username_max_length... OK
  Applying googleautocomplete.0139_auto_20190501_1252... OK
  Applying naturalearth.0053_unescosites... OK
  Applying thumbnail.0001_initial...Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3.4\helpers\pycharm\django_manage.py", line 52, in <module>
    run_command()
  File "C:\Program Files\JetBrains\PyCharm 2018.3.4\helpers\pycharm\django_manage.py", line 46, in run_command
    run_module(manage_file, None, '__main__', True)
  File "C:\Python27\lib\runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\terradiem\terradiem\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
```
Here is what I get when I apply 'migrate'

```
Operations to perform:
  Apply all migrations: account, activatepictures, admin, auth, authtoken, autotweet, contenttypes, fileupload, googleautocomplete, locationreview, naturalearth, searchmydestiny, sessions, sites, socialaccount, thumbnail, trip, usermanagement, welcomepage, world
Running migrations:
  Applying thumbnail.0001_initial...Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3.4\helpers\pycharm\django_manage.py", line 52, in <module>
    run_command()
  File "C:\Program Files\JetBrains\PyCharm 2018.3.4\helpers\pycharm\django_manage.py", line 46, in run_command
    run_module(manage_file, None, '__main__', True)
  File "C:\Python27\lib\runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\terradiem\terradiem\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "C:\Python27\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Python27\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Python27\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Python27\lib\site-packages\django\db\migrations\migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Python27\lib\site-packages\django\db\migrations\operations\models.py", line 97, in database_forwards
    schema_editor.create_model(model)
  File "C:\Python27\lib\site-packages\django\db\backends\base\schema.py", line 319, in create_model
    self.execute(sql, params or None)
  File "C:\Python27\lib\site-packages\django\db\backends\base\schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\raven\contrib\django\client.py", line 123, in execute
    return real_execute(self, sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "thumbnail_kvstore" already exists

Process finished with exit code 1

```

I have no clue what may have generated this.

Any idea ?
What shall I do ?

**Comment by jpuaux** [comment]
Ok, I solved the issue.
I did
`migrate --fake-initial`
And it worked
