### ISSUE TITLE
Thumbnail tag:redis.exceptions.ResponseError: wrong number of arguments for 'auth' command

### ISSUE THREAD

**Issue by danjac** [jazzband/sorl-thumbnail#621]
Just upgraded to Django 3 + latest sorl-thumbnail. Currently *all* thumbnails on site are broken. Was working prior to upgrade.

django==3.0.2
django-redis==4.11.0
redis==3.4.0
sorl-thumbnail==12.6.2

> 2020-01-31T15:42:29.961961+00:00 app[web.1]: if nativestr(self.read_response()) != 'OK':
> 2020-01-31T15:42:29.961962+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
> 2020-01-31T15:42:29.961963+00:00 app[web.1]: raise response
> 2020-01-31T15:42:29.961964+00:00 app[web.1]: redis.exceptions.ResponseError: wrong number of arguments for 'auth' command
> 2020-01-31T15:42:29.981812+00:00 app[web.1]: Thumbnail tag failed
> 2020-01-31T15:42:29.981814+00:00 app[web.1]: Traceback (most recent call last):
> 2020-01-31T15:42:29.981816+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/sorl/thumbnail/templatetags/thumbnail.py", line 59, in render
> 2020-01-31T15:42:29.981817+00:00 app[web.1]: return self._render(context)
> 2020-01-31T15:42:29.981818+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/sorl/thumbnail/templatetags/thumbnail.py", line 139, in _render
> 2020-01-31T15:42:29.981819+00:00 app[web.1]: thumbnail = get_thumbnail(file_, geometry, **options)
> 2020-01-31T15:42:29.981820+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/sorl/thumbnail/shortcuts.py", line 8, in get_thumbnail
> 2020-01-31T15:42:29.981822+00:00 app[web.1]: return default.backend.get_thumbnail(file_, geometry_string, **options)
> 2020-01-31T15:42:29.981823+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/sorl/thumbnail/base.py", line 97, in get_thumbnail
> 2020-01-31T15:42:29.981824+00:00 app[web.1]: cached = default.kvstore.get(thumbnail)
> 2020-01-31T15:42:29.981825+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/sorl/thumbnail/kvstores/base.py", line 26, in get
> 2020-01-31T15:42:29.981826+00:00 app[web.1]: return self._get(image_file.key)
> 2020-01-31T15:42:29.981827+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/sorl/thumbnail/kvstores/base.py", line 145, in _get
> 2020-01-31T15:42:29.981828+00:00 app[web.1]: value = self._get_raw(add_prefix(key, identity))
> 2020-01-31T15:42:29.981831+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/sorl/thumbnail/kvstores/redis_kvstore.py", line 25, in _get_raw
> 2020-01-31T15:42:29.981833+00:00 app[web.1]: return self.connection.get(key)
> 2020-01-31T15:42:29.981834+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 1585, in get
> 2020-01-31T15:42:29.981835+00:00 app[web.1]: return self.execute_command('GET', name)
> 2020-01-31T15:42:29.981836+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 881, in execute_command
> 2020-01-31T15:42:29.981837+00:00 app[web.1]: conn = self.connection or pool.get_connection(command_name, **options)
> 2020-01-31T15:42:29.981838+00:00 app[web.1]: File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1178, in get_connection
>

**Comment by danjac** [comment]
Looks like this might be an issue with the Python redis library:

https://github.com/andymccurdy/redis-py/issues/1274

Please feel free to close this.
